### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Tarkiin** [xditya/WPTagAll#1]
C:\Users\joel_\Desktop\WaBot\WPTagAll\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'LegacyPhoneFeatures')
    at __puppeteer_evaluation_script__:13:76
    at ExecutionContext._evaluateInternal (C:\Users\joel_\Desktop\WaBot\WPTagAll\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\Users\joel_\Desktop\WaBot\WPTagAll\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.initialize (C:\Users\joel_\Desktop\WaBot\WPTagAll\node_modules\whatsapp-web.js\src\Client.js:267:9)

**Comment by xditya** [comment]
It should be fixed now, please `npm install` and run the bot again!
